#!/usr/bin/python3

import serial
import time
import re
ser = serial.Serial('/dev/ttyACM0', 9600, timeout=5)

# read from Arduino
input2 = ser.read()
print ("Read input " + input2.decode("utf-8") + " from Arduino")
while 1:
        # write something back
        command = input("Enter a command")
        ser.write(command.encode("ascii"))
        # read response back from Arduino
        time.sleep(0.5)
        input3 = ser.readlines()
        input3 = str(input3)
        #input3 = re.sub('[^A-Za-z0-9]+', '', input3)
        print (input3)
